version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /tool/vscode-skel
    schedule:
      interval: monthly
    groups:
      vscode-extension-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]
