package skelc_test

import (
	"os"
	"path/filepath"
	"testing"

	"go.yorun.ai/skelc"
)

func TestBackendGenerationRejectsInvalidCompilerVersionBeforeWriting(t *testing.T) {
	for _, version := range []string{"", "  ", "invalid", "0.19.2", "v01.19.2", "v0.19", "v0.14.0", "v0.17.0", "v0.17.1-rc.1"} {
		t.Run(version, func(t *testing.T) {
			root := t.TempDir()
			source := filepath.Join(root, "input.skel")
			if err := os.WriteFile(source, []byte("domain demo.example\npub data Value { name: string }\n"), 0600); err != nil {
				t.Fatal(err)
			}
			out := filepath.Join(root, "generated")
			if err := os.Mkdir(out, 0700); err != nil {
				t.Fatal(err)
			}
			sentinel := filepath.Join(out, "data.go")
			original := "// Code generated by skelc. DO NOT EDIT.\npackage original\n"
			if err := os.WriteFile(sentinel, []byte(original), 0600); err != nil {
				t.Fatal(err)
			}
			input := skelc.Input{SkelIn: source}
			option := skelc.GolangOption{Out: out, CompilerVersion: version}
			if _, err := skelc.CompileGolang(input, option); err == nil {
				t.Fatal("accepted invalid compiler version")
			}
			domain, err := skelc.Parse(input)
			if err != nil {
				t.Fatal(err)
			}
			if err := skelc.GenerateGolang(domain.Domain, option); err == nil {
				t.Fatal("GenerateGolang accepted invalid compiler version")
			}
			data, err := os.ReadFile(sentinel)
			if err != nil || string(data) != original {
				t.Fatalf("output changed: %s, %v", data, err)
			}
		})
	}
}
