package skelc_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.yorun.ai/skelc"
	"go.yorun.ai/skelc/model"
)

func TestPublicOptionsRejectEmptyImportMappings(t *testing.T) {
	if _, err := skelc.Parse(skelc.Input{SkelIn: "input.skel", SkelImports: map[string]string{"demo.user": ""}}); err == nil {
		t.Fatal("expected empty Skel import path error")
	}
	domain := model.NewDomainFromSpec(model.DomainSpec{Name: "demo.test"})
	if err := skelc.GenerateGolang(domain, skelc.GolangOption{
		CompilerVersion: "v0.0.0-dev",
		Out:             filepath.Join(t.TempDir(), "golang"), Imports: map[string]string{"demo.user": ""},
	}); err == nil {
		t.Fatal("expected empty Go import path error")
	}
	if err := skelc.GenerateTypeScript(domain, skelc.TypeScriptOption{ApiOnly: true,
		Out: filepath.Join(t.TempDir(), "typescript"), Imports: map[string]string{"demo.user": ""},
	}); err == nil {
		t.Fatal("expected empty TypeScript import path error")
	}
}

func TestCompileNormalizesGenerationOptionsBeforeReadingInput(t *testing.T) {
	missingInput := skelc.Input{SkelIn: filepath.Join(t.TempDir(), "missing")}
	tests := []struct {
		name     string
		compile  func() error
		expected string
	}{
		{
			name: "Go",
			compile: func() error {
				_, err := skelc.CompileGolang(missingInput, skelc.GolangOption{CompilerVersion: "v0.0.0-dev"})
				return err
			},
			expected: "Go output is required",
		},
		{
			name: "TypeScript",
			compile: func() error {
				_, err := skelc.CompileTypeScript(missingInput, skelc.TypeScriptOption{ApiOnly: true})
				return err
			},
			expected: "TypeScript output is required",
		},
		{
			name: "Skel",
			compile: func() error {
				_, err := skelc.CompileSkeleton(missingInput, skelc.SkeletonOption{})
				return err
			},
			expected: "Skel output is required",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if err := test.compile(); err == nil || !strings.Contains(err.Error(), test.expected) {
				t.Fatalf("expected %q before input loading, got %v", test.expected, err)
			}
		})
	}
}

func TestGeneratorsReturnErrorsForMissingExternalImportMappings(t *testing.T) {
	userDir := t.TempDir()
	writeTestFile(t, filepath.Join(userDir, "domain.skel"), "domain demo.user")
	writeTestFile(t, filepath.Join(userDir, "user.skel"), "domain demo.user\npub data User { id: string }")
	orderDir := t.TempDir()
	writeTestFile(t, filepath.Join(orderDir, "domain.skel"), "domain demo.order")
	writeTestFile(t, filepath.Join(orderDir, "order.skel"), "domain demo.order\nimport demo.user as user\npub data Order { user: user.User }")

	parsed, err := skelc.Parse(skelc.Input{
		SkelIn:      orderDir,
		SkelImports: map[string]string{"demo.user": userDir},
	})
	if err != nil {
		t.Fatalf("parse imported domain: %v", err)
	}

	goErr := skelc.GenerateGolang(parsed.Domain, skelc.GolangOption{CompilerVersion: "v0.0.0-dev", Out: filepath.Join(t.TempDir(), "golang")})
	if goErr == nil || !strings.Contains(goErr.Error(), "missing Go import for domain demo.user") {
		t.Fatalf("expected missing Go import error, got %v", goErr)
	}
	tsErr := skelc.GenerateTypeScript(parsed.Domain, skelc.TypeScriptOption{ApiOnly: true, Out: filepath.Join(t.TempDir(), "typescript")})
	if tsErr == nil || !strings.Contains(tsErr.Error(), "missing TypeScript import for domain demo.user") {
		t.Fatalf("expected missing TypeScript import error, got %v", tsErr)
	}
}

func TestBackendGenerationRejectsInvalidCompilerVersionBeforeWriting(t *testing.T) {
	for _, version := range []string{"", "  ", "invalid", "0.19.2", "v01.19.2", "v0.19", "v0.14.0", "v0.17.0", "v0.17.1-rc.1"} {
		t.Run(version, func(t *testing.T) {
			root := t.TempDir()
			source := filepath.Join(root, "input.skel")
			if err := os.WriteFile(source, []byte("domain demo.example\npub data Value { name: string }\n"), 0600); err != nil {
				t.Fatal(err)
			}
			out := filepath.Join(root, "generated")
			if err := os.Mkdir(out, 0700); err != nil {
				t.Fatal(err)
			}
			sentinel := filepath.Join(out, "data.go")
			original := "// Code generated by skelc. DO NOT EDIT.\npackage original\n"
			if err := os.WriteFile(sentinel, []byte(original), 0600); err != nil {
				t.Fatal(err)
			}
			input := skelc.Input{SkelIn: source}
			option := skelc.GolangOption{Out: out, CompilerVersion: version}
			if _, err := skelc.CompileGolang(input, option); err == nil {
				t.Fatal("accepted invalid compiler version")
			}
			domain, err := skelc.Parse(input)
			if err != nil {
				t.Fatal(err)
			}
			if err := skelc.GenerateGolang(domain.Domain, option); err == nil {
				t.Fatal("GenerateGolang accepted invalid compiler version")
			}
			data, err := os.ReadFile(sentinel)
			if err != nil || string(data) != original {
				t.Fatalf("output changed: %s, %v", data, err)
			}
		})
	}
}

func TestImportValidationOrderIsDeterministic(t *testing.T) {
	domain := model.NewDomainFromSpec(model.DomainSpec{Name: "demo.test"})
	imports := map[string]string{"z": "example.com/z@", "a": "example.com/a@"}
	out := filepath.Join(t.TempDir(), "generated")
	for range 30 {
		goErr := skelc.GenerateGolang(domain, skelc.GolangOption{Out: out, CompilerVersion: "v0.0.0-dev", Imports: imports})
		tsErr := skelc.GenerateTypeScript(domain, skelc.TypeScriptOption{Out: out, ApiOnly: true, Imports: imports})
		for _, err := range []error{goErr, tsErr} {
			if err == nil || !strings.Contains(err.Error(), "example.com/a@") {
				t.Fatalf("unstable first error: %v", err)
			}
		}
	}
}
