package common

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
)

const GeneratedFileMarker = "Code generated by skelc. DO NOT EDIT."

const (
	generatedLineMarker = "// " + GeneratedFileMarker
	generatedJSONMarker = `"_generated": "` + GeneratedFileMarker + `"`
)

// MarkGeneratedFile adds a format-compatible ownership marker to generated
// content. New output formats must define an explicit marker representation so
// the output transaction can distinguish generated files from handwritten
// files without sidecar state.
func MarkGeneratedFile(path string, content string) (string, error) {
	if HasGeneratedFileMarker([]byte(content)) {
		return content, nil
	}

	switch {
	case path == "go.mod", filepath.Ext(path) == ".go", filepath.Ext(path) == ".ts", filepath.Ext(path) == ".skel":
		return generatedLineMarker + "\n\n" + content, nil
	case filepath.Ext(path) == ".json":
		return markGeneratedJSON(content)
	default:
		return "", fmt.Errorf("generated output format for %s does not support an ownership marker", path)
	}
}

func HasGeneratedFileMarker(content []byte) bool {
	return bytes.HasPrefix(content, []byte(generatedLineMarker+"\n")) ||
		bytes.HasPrefix(content, []byte("{\n  "+generatedJSONMarker))
}

func markGeneratedJSON(content string) (string, error) {
	content = strings.TrimSpace(content)
	if !strings.HasPrefix(content, "{") || !strings.HasSuffix(content, "}") {
		return "", fmt.Errorf("generated JSON output must contain a top-level object")
	}

	rest := content[1:]
	if strings.TrimSpace(rest) == "}" {
		return "{\n  " + generatedJSONMarker + "\n}", nil
	}
	return "{\n  " + generatedJSONMarker + "," + rest, nil
}
