// Code generated by skelc. DO NOT EDIT.

package currentpub

import "go.yorun.ai/vine/core/skel"

type Child struct {
	Content skel.Binary `json:"content"`
}

// Clone returns a value-isolated copy of the generated data.
func (v Child) Clone() Child {
	cloned := v
	if v.Content == nil {
		cloned.Content = nil
	} else {
		cloned.Content = make(skel.Binary, len(v.Content))
		copy(cloned.Content, v.Content)
	}
	return cloned
}

type Page[TItem any] struct {
	Items []TItem `json:"items"`
}

// CloneBy returns a copy whose value isolation depends on each clone callback.
// Passing an identity callback does not guarantee isolation for reference-backed values.
func (v Page[TItem]) CloneBy(cloneTItem func(TItem) TItem) Page[TItem] {
	cloned := v
	if v.Items == nil {
		cloned.Items = nil
	} else {
		cloned.Items = make([]TItem, len(v.Items))
		for index0 := range v.Items {
			cloned.Items[index0] = cloneTItem(v.Items[index0])
		}
	}
	return cloned
}
