// Code generated by skelc. DO NOT EDIT.

package currentpub

import "go.yorun.ai/vine/core/skel"

func init() {
	skel.RegisterDomainSchema(_DomainSchema)
}

var _DomainSchema = &skel.DomainSchema{
	Domain: "demo.current",
	Hash:   "490baf10",
	Full:   false,
	Generated: &skel.GeneratedInfo{
		CompilerVersion: "v0.17.1",
	},

	Data: []*skel.DataSchema{
		{
			Name:     "Child",
			SkelName: "demo.current.Child",
			Hash:     "a6fe991e",
			Members: []*skel.MemberSchema{
				{
					Name: "content",
					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarBinary,
					},
				},
			},
		},
		{
			Name:     "Page",
			SkelName: "demo.current.Page",
			Hash:     "0d45fb03",
			TypeParameters: []string{
				"TItem",
			},
			Members: []*skel.MemberSchema{
				{
					Name: "items",
					Type: &skel.TypeSchema{
						Kind: skel.TypeKindList,
						Element: &skel.TypeSchema{
							Kind: skel.TypeKindTypeParameter,
							Name: "TItem",
						},
					},
				},
			},
		},
	},
}
