package cli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.yorun.ai/skelc/internal/command"
)

func TestGenerationVersionErrorsAreInvalidArgumentsAndPreserveOutput(t *testing.T) {
	for _, flags := range [][]string{
		{"--go-vine-version", "v01.15.7"},
		{"--api", "--go-vrpc-version", "v01.12.0"},
		{"--api", "--go-vine-version", "v0.19.0"},
		{"--go-vrpc-version", "v0.12.0"},
		{"--go-import", "unused=example.com/dependency@v01.2.3"},
		{"--go-import", "first=example.com/dependency@v1.0.0", "--go-import", "second=example.com/dependency@v1.1.0"},
	} {
		t.Run(flags[len(flags)-1], func(t *testing.T) {
			root := t.TempDir()
			source := filepath.Join(root, "source.skel")
			if err := os.WriteFile(source, []byte("domain demo.test\napi service TestApiService { method ping {} }\n"), 0600); err != nil {
				t.Fatal(err)
			}
			out := filepath.Join(root, "generated")
			if err := os.Mkdir(out, 0700); err != nil {
				t.Fatal(err)
			}
			sentinel := filepath.Join(out, "data.go")
			original := "// Code generated by skelc. DO NOT EDIT.\npackage original\n"
			if err := os.WriteFile(sentinel, []byte(original), 0600); err != nil {
				t.Fatal(err)
			}
			args := append([]string{"gen", "go-module", "--skel-in", source, "--go-out", out, "--go-module", "example.com/generated"}, flags...)
			result := Run(args)
			var failure command.Error
			if err := json.Unmarshal([]byte(result.Stdout), &failure); err != nil {
				t.Fatal(err)
			}
			if result.ExitCode != command.ExitCodeError || failure.Code != command.ErrorCodeInvalidArgument {
				t.Fatalf("wrong classification: %+v", result)
			}
			got, err := os.ReadFile(sentinel)
			if err != nil || string(got) != original {
				t.Fatalf("output changed on failure: %s %v", got, err)
			}
		})
	}
}

func TestTypeScriptDependencyConflictIsInvalidArgumentAndPreservesOutput(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"first.skel":  "domain first\npub data First { name: string }\n",
		"second.skel": "domain second\npub data Second { name: string }\n",
		"main.skel":   "domain demo.main\nimport first as first\nimport second as second\npub data Both { first: first.First\nsecond: second.Second }\n",
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(root, name), []byte(content), 0600); err != nil {
			t.Fatal(err)
		}
	}
	out := filepath.Join(root, "generated")
	if err := os.Mkdir(out, 0700); err != nil {
		t.Fatal(err)
	}
	sentinel := filepath.Join(out, "data.ts")
	original := "// Code generated by skelc. DO NOT EDIT.\nexport type Original = string;\n"
	if err := os.WriteFile(sentinel, []byte(original), 0600); err != nil {
		t.Fatal(err)
	}
	result := Run([]string{"gen", "ts", "--api", "--ts-as-module", "--ts-module", "@example/generated", "--ts-out", out, "--skel-in", filepath.Join(root, "main.skel"), "--skel-import", "first=" + filepath.Join(root, "first.skel"), "--skel-import", "second=" + filepath.Join(root, "second.skel"), "--ts-import", "first=@example/shared@1.0.0", "--ts-import", "second=@example/shared@2.0.0"})
	var failure command.Error
	if err := json.Unmarshal([]byte(result.Stdout), &failure); err != nil {
		t.Fatal(err)
	}
	if result.ExitCode != command.ExitCodeError || failure.Code != command.ErrorCodeInvalidArgument || !strings.Contains(failure.Message, "conflicting TypeScript dependency versions") {
		t.Fatalf("wrong conflict result: %+v", result)
	}
	got, err := os.ReadFile(sentinel)
	if err != nil || string(got) != original {
		t.Fatalf("output changed on conflict: %s %v", got, err)
	}
}

func TestInvalidModuleMetadataPreservesOutputs(t *testing.T) {
	for _, test := range []struct {
		name   string
		domain string
		flags  []string
	}{
		{"go-module", "demo.test", []string{"gen", "go-module", "--go-out", "OUT", "--go-module", "invalid module"}},
		{"go-pub-module", "demo.test", []string{"gen", "go-module", "--go-out", "OUT", "--go-module", "example.com/generated", "--go-pub-out", "PUB", "--go-pub-module", "bad pub module"}},
		{"go-prefix", "demo.test", []string{"gen", "go-module", "--go-out", "OUT", "--go-module-prefix", "invalid prefix"}},
		{"go-derived-module", "demo.con", []string{"gen", "go-module", "--go-out", "OUT", "--go-module-prefix", "example.com/generated"}},
		{"ts-name", "demo.test", []string{"gen", "ts", "--api", "--ts-as-module", "--ts-out", "OUT", "--ts-module", "@demo/bad\"name"}},
		{"ts-scope", "demo.test", []string{"gen", "ts", "--api", "--ts-as-module", "--ts-out", "OUT", "--ts-module-scope", "@bad scope"}},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			out, pub := filepath.Join(root, "generated"), filepath.Join(root, "public")
			original := "// Code generated by skelc. DO NOT EDIT.\noriginal content\n"
			for _, dir := range []string{out, pub} {
				if err := os.Mkdir(dir, 0700); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(dir, "sentinel.go"), []byte(original), 0600); err != nil {
					t.Fatal(err)
				}
			}
			source := filepath.Join(root, "source.skel")
			if err := os.WriteFile(source, []byte("domain "+test.domain+"\npub data Value { name: string }\n"), 0600); err != nil {
				t.Fatal(err)
			}
			args := append([]string(nil), test.flags...)
			for i, v := range args {
				if v == "OUT" {
					args[i] = out
				}
				if v == "PUB" {
					args[i] = pub
				}
			}
			args = append(args, "--skel-in", source)
			result := Run(args)
			var failure command.Error
			if err := json.Unmarshal([]byte(result.Stdout), &failure); err != nil {
				t.Fatal(err)
			}
			if result.ExitCode != command.ExitCodeError || failure.Code != command.ErrorCodeInvalidArgument {
				t.Fatalf("unexpected result: %+v", result)
			}
			for _, dir := range []string{out, pub} {
				data, err := os.ReadFile(filepath.Join(dir, "sentinel.go"))
				if err != nil || string(data) != original {
					t.Fatalf("modified output %s: %s %v", dir, data, err)
				}
			}
		})
	}
}
